version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: carparkinglot-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./application/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
