version: '3.8'

services:
  carpark-app:
    image: carpark:latest
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/carpark
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_REDIS_HOST=cache
      - SPRING_REDIS_PORT=6379
    depends_on:
      - db
      - cache
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgres
      - ./application/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
volumes:
  db_data:
    driver: local
